" vimrc
" Author: Goznauk [goznauk@nhnnext.org]
" 2014/04/05 updated
"

set nocompatible
filetype on
filetype off





" EnCoding
set enc=UTF-8
set fileencodings=UTF-8
set fencs=utf8,euc-kr,cp949,cp932,euc-jp,shift-jis,big5,latin1,ucs-2le
set visualbell
set backspace=indent,eol,start
set statusline=%h%F%m%r%=[%l:%c(%p%%)]
set tabstop=2
set shiftwidth=2
set cindent
set autoindent
set smartindent
"filetype indent on
set history=15
set ruler
set showcmd
set nobackup
set foldmethod=marker
set hlsearch
set background=dark
set number
set visualbell
set noswapfile
"set paste!                         "Use when Paste sth

syntax on

map <F1> <ESC>:help<CR>
map <F2> <ESC>:NERDTree<CR>
map <F3> <ESC>:w<CR>
map <F4> <ESC>:wq<CR>

map <F6> <ESC>:vs<CR>
map <F7> <ESC>:sp<CR>
map <F8> <ESC>:new<CR>
map <F9> <ESC>:close<CR>
map <C-TAB> <C-p>

" Pydiction
let g:pydiction_location = '/Users/goznauk/.vim/bundle/Pydiction/complete-dict'


" Vundle
set nocompatible              " be iMproved
filetype on
filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'
Bundle 'tpope/vim-fugitive'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'tpope/vim-rails.git'
" vim-scripts repos
Bundle 'L9'
Bundle 'FuzzyFinder'
" non-GitHub repos
Bundle 'git://git.wincent.com/command-t.git'
" Git repos on your local machine (i.e. when working on your own plugin)
" Bundle 'file://Users/usrname/path/to/plugin'



" goznauk installed
Bundle 'Pydiction'
Bundle 'The-NERD-tree'

Bundle 'Source-Explorer-srcexpl.vim'
Bundle 'pyflakes'
Bundle 'Python-Syntax'
" Bundle 'Valloric/YouCompleteMe'
Bundle 'AutoComplPop'


" gyuwon gave me

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install (update) bundles
" :BundleSearch(!) foo - search (or refresh cache first) for foo
" :BundleClean(!)      - confirm (or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle commands are not allowed.
